sudo: required
language: python
python: "3.6"

before_install:
  - pip install --upgrade pip
  - pip install -U pip setuptools
  - pip --version

install:
  - pip install Cython
  - pip install -r requirements.txt

script:
  - python -m unittest discover
  - make build
  - make run_build-test
