sudo: required
language: python
python: "3.6"

before_install:
  - pip install --upgrade pip
  - pip --version

install:
  - pip install Cython
  - pip install -r requirements.txt

script: python -m unittest discover
