.PHONY: init
init:
	pip3 install -r requirements.txt

.PHONY: test
test:
	python3 -m unittest discover

.PHONY: run
run:
	python3 application/querio.py

.PHONY: build
build:
	pyinstaller -y --clean querio.spec
