.PHONY: init
init:
	pip install -r requirements.txt

.PHONY: test
test:
	python3 -m unittest discover

.PHONY: run
run:
	python3 application/querio.py

.PHONY: build
build:
	pyinstaller -y --clean \
	-p application/ \
	--additional-hooks-dir hookfiles \
	--add-data application/configuration.ini:application \
	--add-data application/userInterface.kv:application \
	application/querio.py
