version: '3.2'
 
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: queriouser
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: queriodb


  db-populator:
    build: .
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "-u", "init_database.py", "10000000", "rows.csv"]

  normalized-db-populator:
    build: .
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "-u", "init_normalized_database.py", "10000"]
